export enum DepartmentValue {
  Anesthesiology = 'anesthesiology',
  Cardiology = 'cardiology',
  Dermatology = 'dermatology',
  EmergencyMedicine = 'emergency_medicine',
  Endocrinology = 'endocrinology',
  ENT = 'ent',
  Gastroenterology = 'gastroenterology',
  GeneralSurgery = 'general_surgery',
  Gynecology = 'gynecology',
  Nephrology = 'nephrology',
  Neurology = 'neurology',
  Ophthalmology = 'ophthalmology',
  Oncology = 'oncology',
  Orthopedics = 'orthopedics',
  Pathology = 'pathology',
  Pediatrics = 'pediatrics',
  PlasticSurgery = 'plastic_surgery',
  Psychiatry = 'psychiatry',
  Pulmonology = 'pulmonology',
  Rheumatology = 'rheumatology',
}
