export const POSSIBLE_SYMPTOMS = [
  'fever',
  'cough',
  'headache',
  'fatigue',
  'sore throat',
  'nausea',
  'vomiting',
  'diarrhea',
  'chills',
  'shortness of breath',
  'muscle aches',
  'runny nose',
  'congestion',
  'loss of taste',
  'loss of smell',
  'yellowish tint',
  'dark-colored pee',
  'pale-colored poop',
  'tired',
  'confused',
  'itchy skin',
  'weight loss',
  'abdominal pain',
  'abnormal gait',
  'abnormal heart rhythm',
  'abnormal liver function',
  'abnormal menstruation',
  'abnormal reflexes',
  'acid reflux',
  'acne',
  'agitation',
  'alopecia',
  'amnesia',
  'anemia',
  'angina',
  'anxiety',
  'apathy',
  'appetite loss',
  'arm pain',
  'arthritis',
  'asthma',
  'back pain',
  'balance problems',
  'bloating',
  'blurred vision',
  'bone pain',
  'bradycardia',
  'bruising',
  'burning sensation',
  'chest pain',
  'chronic fatigue',
  'clumsiness',
  'cold hands and feet',
  'confusion',
  'constipation',
  'coughing blood',
  'cramps',
  'cyanosis',
  'dandruff',
  'dehydration',
  'depression',
  'dizziness',
  'dry eyes',
  'dry mouth',
  'dry skin',
  'dysphagia',
  'ear pain',
  'eczema',
  'edema',
  'elevated blood pressure',
  'enlarged lymph nodes',
  'eye pain',
  'facial pain',
  'fainting',
  'fast heartbeat',
  'fatty stools',
  'feeling cold',
  'feeling hot',
  'flatulence',
  'flushing',
  'frequent urination',
  'gas',
  'gastrointestinal bleeding',
  'hallucinations',
  'hand tremors',
  'head pressure',
  'heart palpitations',
  'hematuria',
  'hiccups',
  'hoarseness',
  'hyperactivity',
  'hypertension',
  'hypotension',
  'impotence',
  'incontinence',
  'increased appetite',
  'indigestion',
  'inflammation',
  'insomnia',
  'irregular heartbeat',
  'irritability',
  'itching',
  'joint pain',
  'joint stiffness',
  'jaundice',
  'knee pain',
  'lack of concentration',
  'lack of coordination',
  'leg pain',
  'lethargy',
  'lightheadedness',
  'lip swelling',
  'low back pain',
  'low blood pressure',
  'low-grade fever',
  'malaise',
  'memory loss',
  'mental confusion',
  'mood swings',
  'mouth ulcers',
  'muscle cramps',
  'muscle weakness',
  'nasal congestion',
  'nausea',
  'neck pain',
  'night sweats',
  'numbness',
  'painful urination',
  'palpitations',
  'panic attacks',
  'paralysis',
  'pins and needles',
  'poor circulation',
  'postnasal drip',
  'rash',
  'red eyes',
  'restlessness',
  'runny nose',
  'seizures',
  'shortness of breath',
  'skin rashes',
  'sleep apnea',
  'sneezing',
  'sore throat',
  'stomach cramps',
  'stomach pain',
  'stomach upset',
  'stress',
  'sweating',
  'swollen ankles',
  'swollen glands',
  'swollen joints',
  'swollen legs',
  'tenderness',
  'tingling',
  'tinnitus',
  'tremors',
  'trouble sleeping',
  'unexplained weight loss',
  'unsteady gait',
  'urinary incontinence',
  'urinary urgency',
  'vertigo',
  'vomiting',
  'weakness',
  'weight gain',
  'wheezing',
];
